"""Alter name of role unique

Revision ID: 25d500075997
Revises: e95368eebabb
Create Date: 2025-03-08 13:26:20.221402

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25d500075997"
down_revision: Union[str, None] = "e95368eebabb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("login_history_id_uq", "login_history", ["id"])
    op.create_unique_constraint("roles_name_uq", "roles", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("roles_name_uq", "roles", type_="unique")
    op.drop_constraint("login_history_id_uq", "login_history", type_="unique")
    # ### end Alembic commands ###
