"""Add social network

Revision ID: 3d6c57f43146
Revises: 6c701fd5f452
Create Date: 2025-04-26 01:59:37.312894

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d6c57f43146"
down_revision: Union[str, None] = "6c701fd5f452"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_network",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usersocial",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("social_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["social_id"], ["social_network.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "social_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersocial")
    op.drop_table("social_network")
    # ### end Alembic commands ###
