"""Alter name of section unique

Revision ID: 5c3e4ef3c795
Revises: 25d500075997
Create Date: 2025-03-08 16:01:27.235059

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c3e4ef3c795"
down_revision: Union[str, None] = "25d500075997"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("sections_name_uq", "sections", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sections_name_uq", "sections", type_="unique")
    # ### end Alembic commands ###
