"""Add created to login history

Revision ID: ba04fb199eda
Revises: 5c3e4ef3c795
Create Date: 2025-03-08 21:03:56.670722

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba04fb199eda"
down_revision: Union[str, None] = "5c3e4ef3c795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_history", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login_history", "created_at")
    # ### end Alembic commands ###
